package tarundFBLA.Forms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class StudentForm extends HorizontalLayout {
    public TextField firstName;
    public TextField lastName;
    public TextField grade;
    public TextField classRoom;
    public TextField studentId;
    public Button delete;
    public Button save;
    public Button cancel;
    public Button add;
    public Label nSave;


    public StudentForm(){
        firstName = new TextField();
        lastName = new TextField();
        grade = new TextField();
        classRoom = new TextField();
        studentId = new TextField();
        delete = new Button();
        save = new Button();
        cancel = new Button();
        add = new Button();
        nSave = new Label();
        //Design.read(this);}
}


}